version: 2

defaults: &defaults
    docker:
    - image: malco414/dockerfile_tfnotify
    working_directory: ~/terraformcipractice

jobs:
  fmt:
    <<: *defaults
    steps:
      - checkout
      - run:
        name: "terraform fmt"
        command: |
          terraform fmt -diff=true -check=true

  plan:
    <<: *defaults
    steps:
      - checkout
      - run:
        name: "terraform init"
        command: |
          terraform init -input=false
      - run:
        name: "check terraform format"
        command: |
          terraform plan | tfnotify plan

workflows:
  version: 2
  terraform-workflow:
    jobs:
      - fmt
      - plan